-- 코드를 입력하세요
SELECT car.CAR_ID, car.CAR_TYPE, ROUND((DAILY_FEE * (1 - DISCOUNT_RATE / 100) * 30)) AS FEE
FROM
(SELECT *
 FROM CAR_RENTAL_COMPANY_CAR
 WHERE CAR_TYPE = 'SUV' OR CAR_TYPE = '세단'
 ) as car
JOIN
(SELECT *
 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
 WHERE DURATION_TYPE LIKE '%30%'
 ) as discount ON discount.CAR_TYPE = car.CAR_TYPE
WHERE car.CAR_ID NOT IN(
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= '2022-11-30'
AND END_DATE >= '2022-11-01')
GROUP BY car.CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC