SELECT fi2.ID, fn.FISH_NAME, fi1.LENGTH
FROM FISH_NAME_INFO as fn
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    ) as fi1 ON fi1.FISH_TYPE = fn.FISH_TYPE
JOIN FISH_INFO as fi2 ON fi2.LENGTH = fi1.LENGTH AND fi2.FISH_TYPE = fi1.FISH_TYPE;